### ISSUE TITLE
Swagger 2 to OpenAPI 3 endpoint using Lucy's converter

### ISSUE THREAD

**Issue by pcgamer1** [postmanlabs/api-spec-converter#10]
## Description
As a developer,
I want convert an api schema from OAS2 to OAS3,
so that I can follow the latest OpenAPI version and use its features.

### Update [Required]
- [x] API Specification in Postman (follow API first)
- [x] Endpoint
- [x] Accept a json/yaml Swagger (OpenAPI 2.0) spec, return json/yaml OpenAPI 3.0
- [x] Accepts json -> json & yaml -> yaml & json -> yaml & yaml -> json
- [x] file/string = file -> string & file-> file
- [x] Tests

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation

6 hours

**Comment by meenakshi-dhanani** [comment]
@pcgamer1 
I've modified the use case a bit, to highlight intent - try doing that next time. 
As a makes you understand the client for who you're building this feature, I want is your goal, and so that is the value that you bring to the client. Highlighting these before you build is important. 

Also added acceptance criteria for the API schema to follow API-first as discussed.
